AWSTemplateFormatVersion: '2010-09-09'
Description: E-Commerce Microservices Infrastructure - Free Tier Compliant with Automated Deployment

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access

  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t2.micro
    Description: EC2 instance type

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
    Description: Amazon Linux 2023 AMI via SSM

  GitHubRepoUrl:
    Type: String
    Default: https://github.com/diazdennis/microservice-e-commerce.git
    Description: GitHub repository URL to clone

  AppKey:
    Type: String
    NoEcho: true
    MinLength: 32
    Description: Laravel APP_KEY (base64, 32+ chars)

  MySQLRootPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: MySQL root password

  MySQLAppPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: MySQL app user password

  AWSRegion:
    Type: String
    Default: ap-southeast-1
    AllowedValues:
      - us-east-1
      - us-west-2
      - ap-southeast-1
      - ap-southeast-2
      - eu-west-1
    Description: Region for SES SMTP endpoint

  SESUsername:
    Type: String
    NoEcho: true
    Description: SES SMTP username

  SESPassword:
    Type: String
    NoEcho: true
    Description: SES SMTP password

  MailFromAddress:
    Type: String
    Default: dennis.diaz.tech@gmail.com
    Description: Verified SES sender email

  MailFromName:
    Type: String
    Default: "E-Commerce Store"
    Description: Email sender name

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-VPC'

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-PublicSubnet'

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-SG'

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSESFullAccess

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  SESEmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref MailFromAddress

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          AssociatePublicIpAddress: true
          SubnetId: !Ref PublicSubnet
          GroupSet:
            - !Ref WebSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          exec > /var/log/user-data.log 2>&1

          dnf update -y
          dnf install -y docker git curl nodejs npm

          systemctl start docker
          systemctl enable docker
          usermod -aG docker ec2-user
          sleep 10

          # Docker Compose v2
          curl -L "https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

          cd /home/ec2-user
          rm -rf microservice-e-commerce
          git clone ${GitHubRepoUrl} microservice-e-commerce
          cd microservice-e-commerce
          chown -R ec2-user:ec2-user .

          # Build frontend
          if [ -d frontend ]; then
            cd frontend
            npm install && npm run build
            cd ..
          else
            echo "ERROR: frontend directory missing"
            exit 1
          fi

          # Shared .env
          cat > .env << EOF
          MYSQL_ROOT_PASSWORD=${MySQLRootPassword}
          MYSQL_USER=appuser
          MYSQL_PASSWORD=${MySQLAppPassword}
          APP_KEY=base64:${AppKey}
          CORS_ALLOWED_ORIGINS=*
          EOF

          # Service .env files
          mkdir -p services/catalog services/checkout services/email

          cat > services/catalog/.env << EOF
          APP_ENV=production
          APP_KEY=base64:${AppKey}
          APP_DEBUG=false
          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_PORT=3306
          DB_DATABASE=catalog_db
          DB_USERNAME=appuser
          DB_PASSWORD=${MySQLAppPassword}
          CORS_ALLOWED_ORIGINS=*
          EOF

          cat > services/checkout/.env << EOF
          APP_ENV=production
          APP_KEY=base64:${AppKey}
          APP_DEBUG=false
          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_PORT=3306
          DB_DATABASE=checkout_db
          DB_USERNAME=appuser
          DB_PASSWORD=${MySQLAppPassword}
          CATALOG_SERVICE_URL=http://catalog:8000
          EMAIL_SERVICE_URL=http://email:8000
          CORS_ALLOWED_ORIGINS=*
          EOF

          cat > services/email/.env << EOF
          APP_ENV=production
          APP_KEY=base64:${AppKey}
          APP_DEBUG=false
          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_PORT=3306
          DB_DATABASE=email_db
          DB_USERNAME=appuser
          DB_PASSWORD=${MySQLAppPassword}
          MAIL_MAILER=smtp
          MAIL_HOST=email-smtp.${AWSRegion}.amazonaws.com
          MAIL_PORT=587
          MAIL_USERNAME=${SESUsername}
          MAIL_PASSWORD=${SESPassword}
          MAIL_ENCRYPTION=tls
          MAIL_FROM_ADDRESS=${MailFromAddress}
          MAIL_FROM_NAME="${MailFromName}"
          CORS_ALLOWED_ORIGINS=*
          EOF

          cat > frontend/.env.production << EOF
          VITE_CATALOG_API=/api
          VITE_CHECKOUT_API=/api/checkout
          EOF

          # Start everything
          docker-compose up -d --build

          # Wait for MySQL
          for i in {1..60}; do
            docker-compose exec -T mysql mysqladmin ping -hlocalhost --silent && break
            sleep 3
          done

          # Migrations with retry
          for service in catalog checkout email; do
            for attempt in {1..10}; do
              if docker-compose exec -T $service php artisan migrate --force --seed >/dev/null 2>&1; then
                echo "$service migrations OK"
                break
              fi
              sleep 10
            done
          done

          PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)
          echo "SUCCESS! App running at http://$PUBLIC_IP" > /home/ec2-user/DEPLOYMENT-SUCCESS.txt

      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-EC2'

  EIP:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment
    Properties:
      Domain: vpc

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      InstanceId: !Ref EC2Instance

Outputs:
  WebsiteURL:
    Description: Your e-commerce site URL
    Value: !Sub 'http://${EIP.PublicIp}'
  SSHCommand:
    Description: SSH into instance
    Value: !Sub 'ssh -i ${KeyName}.pem ec2-user@${EIP.PublicIp}'
  SESNote:
    Description: Verify SES email
    Value: !Sub 'Check ${MailFromAddress} for AWS verification email'