AWSTemplateFormatVersion: '2010-09-09'
Description: 'E-Commerce Microservices Infrastructure - Free Tier Compliant with Automated Deployment'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of an existing EC2 KeyPair for SSH access"

  InstanceType:
    Type: String
    Description: "EC2 instance type (t3.micro for free tier in ap-southeast-2)"
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t2.micro

  LatestAmiId:
    Type: String
    Description: "Amazon Linux 2023 AMI ID for your region. The deployment script will automatically fetch this, or you can find it in the EC2 console. To get it manually, run: aws ssm get-parameter --name /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64 --region <your-region> --query Parameter.Value --output text"

  GitHubRepoUrl:
    Type: String
    Description: "GitHub repository URL to clone (e.g., https://github.com/username/e-commerce-microservices.git)"
    Default: https://github.com/diazdennis/microservice-e-commerce.git

  AppKey:
    Type: String
    Description: "Laravel application key (generate with: openssl rand -base64 32)"
    NoEcho: true

  MySQLRootPassword:
    Type: String
    Description: "MySQL root password (strong password recommended)"
    NoEcho: true
    MinLength: 8

  MySQLAppPassword:
    Type: String
    Description: "MySQL application user password"
    NoEcho: true
    MinLength: 8

  AWSRegion:
    Type: String
    Description: "AWS Region for SES"
    Default: ap-southeast-1

  SESUsername:
    Type: String
    Description: "AWS SES SMTP Username"
    NoEcho: true

  SESPassword:
    Type: String
    Description: "AWS SES SMTP Password"
    NoEcho: true

  MailFromAddress:
    Type: String
    Description: "Verified email address in AWS SES (sender email)"
    Default: noreply@e-commerce.com

  MailFromName:
    Type: String
    Description: "Email sender name"
    Default: "E-Commerce Store"

Resources:
  # VPC and Networking
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpc'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-igw'

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-subnet'

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-rt'

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Security Group
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web server
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-sg'

  # IAM Role for EC2 to use SES
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-ec2-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ec2-role'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-instance-profile'
      Roles:
        - !Ref EC2Role

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnet
          GroupSet:
            - !Ref WebSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          
          # Update system
          dnf update -y
          
          # Install Docker
          dnf install -y docker git
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ec2-user
          
          # Install Docker Compose
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
          # Install Node.js and npm for frontend build
          dnf install -y nodejs npm
          
          # Clone repository
          cd /home/ec2-user
          git clone ${GitHubRepoUrl} microservice-e-commerce
          cd microservice-e-commerce
          
          # Build frontend (if frontend directory exists)
          if [ -d "frontend" ]; then
            cd frontend
            npm install || echo "npm install failed, continuing..."
            npm run build || echo "npm build failed, continuing..."
            cd ..
          else
            echo "Frontend directory not found, skipping build"
          fi
          
          # Create .env file
          cat > .env <<ENVFILE
          # Application Key
          APP_KEY=${AppKey}
          
          # AWS SES Configuration
          AWS_REGION=${AWSRegion}
          AWS_SES_SMTP_USERNAME=${SESUsername}
          AWS_SES_SMTP_PASSWORD=${SESPassword}
          MAIL_FROM_ADDRESS=${MailFromAddress}
          MAIL_FROM_NAME=${MailFromName}
          
          # Database Configuration
          MYSQL_ROOT_PASSWORD=${MySQLRootPassword}
          MYSQL_USER=appuser
          MYSQL_PASSWORD=${MySQLAppPassword}
          ENVFILE
          
          # Wait for Docker to be ready
          sleep 10
          
          # Start services
          echo "Starting Docker Compose services..."
          docker-compose up -d --build || {
            echo "Docker Compose failed, checking logs..."
            docker-compose logs
            exit 1
          }
          
          # Wait for services to be ready
          echo "Waiting for services to be ready..."
          sleep 30
          
          # Run database migrations
          echo "Running database migrations..."
          docker-compose exec -T catalog php artisan migrate --seed || echo "Catalog migration failed"
          docker-compose exec -T checkout php artisan migrate || echo "Checkout migration failed"
          docker-compose exec -T email php artisan migrate || echo "Email migration failed"
          
          # Log completion
          echo "Deployment completed successfully!" > /home/ec2-user/deployment-status.txt
          echo "Application URL: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)" >> /home/ec2-user/deployment-status.txt

      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ec2'

  # Elastic IP (optional - free if instance is running)
  EIP:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-eip'

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      InstanceId: !Ref EC2Instance

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EIP.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'

  PublicDNS:
    Description: Public DNS hostname of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName
    Export:
      Name: !Sub '${AWS::StackName}-PublicDNS'

  WebsiteURL:
    Description: Website URL (IP address)
    Value: !Sub 'http://${EIP.PublicIp}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'

  WebsiteURLDNS:
    Description: Website URL (DNS hostname)
    Value: !Sub 'http://${EC2Instance.PublicDnsName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURLDNS'

  SSHCommand:
    Description: SSH command to connect to the instance
    Value: !Sub 'ssh -i dennis-ec2.pem ec2-user@${EIP.PublicIp}'
