AWSTemplateFormatVersion: '2010-09-09'
Description: 'E-Commerce Microservices Infrastructure - Free Tier Compliant with Automated Deployment'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of an existing EC2 KeyPair for SSH access"

  InstanceType:
    Type: String
    Description: "EC2 instance type (t3.micro for free tier in ap-southeast-2)"
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t2.micro

  LatestAmiId:
    Type: String
    Description: "Amazon Linux 2023 AMI ID for your region. The deployment script will automatically fetch this, or you can find it in the EC2 console. To get it manually, run: aws ssm get-parameter --name /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64 --region <your-region> --query Parameter.Value --output text"

  GitHubRepoUrl:
    Type: String
    Description: "GitHub repository URL to clone (e.g., https://github.com/username/e-commerce-microservices.git)"
    Default: https://github.com/diazdennis/microservice-e-commerce.git

  AppKey:
    Type: String
    Description: "Laravel application key (generate with: openssl rand -base64 32)"
    NoEcho: true

  MySQLRootPassword:
    Type: String
    Description: "MySQL root password (strong password recommended)"
    NoEcho: true
    MinLength: 8

  MySQLAppPassword:
    Type: String
    Description: "MySQL application user password"
    NoEcho: true
    MinLength: 8

  AWSRegion:
    Type: String
    Description: "AWS Region for SES"
    Default: ap-southeast-1

  SESUsername:
    Type: String
    Description: "AWS SES SMTP Username"
    NoEcho: true

  SESPassword:
    Type: String
    Description: "AWS SES SMTP Password"
    NoEcho: true

  MailFromAddress:
    Type: String
    Description: "Verified email address in AWS SES (sender email)"
    Default: noreply@e-commerce.com

  MailFromName:
    Type: String
    Description: "Email sender name"
    Default: "E-Commerce Store"

Resources:
  # VPC and Networking
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-vpc'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-igw'

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-subnet'

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-public-rt'

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Security Group
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for web server
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: SSH access
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-sg'

  # IAM Role for EC2 to use SES
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-ec2-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ec2-role'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-instance-profile'
      Roles:
        - !Ref EC2Role

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref PublicSubnet
          GroupSet:
            - !Ref WebSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Update system
          dnf update -y

          # Install Docker
          dnf install -y docker git
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ec2-user

          # Install Docker Compose
          curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

          # Install Node.js and npm for frontend build
          dnf install -y nodejs npm

          # Clone repository
          cd /home/ec2-user
          git clone ${GitHubRepoUrl} microservice-e-commerce
          cd microservice-e-commerce

          # Build frontend (if frontend directory exists)
          if [ -d "frontend" ]; then
            echo "Building frontend..."
            cd frontend
            npm install
            if [ $? -eq 0 ]; then
              npm run build
              if [ $? -ne 0 ]; then
                echo "ERROR: Frontend build failed!"
                exit 1
              fi
            else
              echo "ERROR: npm install failed!"
              exit 1
            fi
            cd ..
            echo "Frontend build completed successfully"
          else
            echo "ERROR: Frontend directory not found!"
            exit 1
          fi

          # Verify frontend dist exists
          if [ ! -d "frontend/dist" ] || [ -z "$(ls -A frontend/dist)" ]; then
            echo "ERROR: Frontend dist directory is empty or missing!"
            exit 1
          fi

          # Create shared .env file for docker-compose variables
          echo "Creating shared .env file..."
          cat > .env << 'EOF'
          # Shared Docker Compose variables
          MYSQL_ROOT_PASSWORD=${MySQLRootPassword}
          MYSQL_USER=appuser
          MYSQL_PASSWORD=${MySQLAppPassword}
          APP_KEY=base64:${AppKey}
          CORS_ALLOWED_ORIGINS=*
          EOF

          # Create service-specific .env files
          echo "Creating service-specific .env files..."

          # Catalog service .env
          mkdir -p services/catalog
          cat > services/catalog/.env << 'EOF'
          APP_NAME="Catalog Service"
          APP_ENV=production
          APP_KEY=base64:${AppKey}
          APP_DEBUG=false
          APP_URL=http://localhost

          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_PORT=3306
          DB_DATABASE=catalog_db
          DB_USERNAME=appuser
          DB_PASSWORD=apppassword

          CORS_ALLOWED_ORIGINS=*
          EOF

          # Checkout service .env
          mkdir -p services/checkout
          cat > services/checkout/.env << 'EOF'
          APP_NAME="Checkout Service"
          APP_ENV=production
          APP_KEY=base64:${AppKey}
          APP_DEBUG=false
          APP_URL=http://localhost

          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_PORT=3306
          DB_DATABASE=checkout_db
          DB_USERNAME=appuser
          DB_PASSWORD=apppassword

          # Service URLs (Docker network hostnames - internal communication)
          CATALOG_SERVICE_URL=http://catalog
          EMAIL_SERVICE_URL=http://email

          CORS_ALLOWED_ORIGINS=*
          EOF

          # Email service .env
          mkdir -p services/email
          cat > services/email/.env << 'EOF'
          APP_NAME="Email Service"
          APP_ENV=production
          APP_KEY=base64:${AppKey}
          APP_DEBUG=false
          APP_URL=http://localhost

          DB_CONNECTION=mysql
          DB_HOST=mysql
          DB_PORT=3306
          DB_DATABASE=email_db
          DB_USERNAME=appuser
          DB_PASSWORD=apppassword

          # AWS SES Configuration
          MAIL_MAILER=smtp
          MAIL_HOST=email-smtp.${AWSRegion}.amazonaws.com
          MAIL_PORT=587
          MAIL_USERNAME=${SESUsername}
          MAIL_PASSWORD=${SESPassword}
          MAIL_ENCRYPTION=tls
          MAIL_FROM_ADDRESS=${MailFromAddress}
          MAIL_FROM_NAME="${MailFromName}"
          AWS_REGION=${AWSRegion}

          CORS_ALLOWED_ORIGINS=*
          EOF

          # Create frontend production environment
          mkdir -p frontend
          cat > frontend/.env.production << 'EOF'
          # Frontend API endpoints (relative paths work with Nginx proxy)
          VITE_CATALOG_API=/api
          VITE_CHECKOUT_API=/api
          # Note: No email service URL - frontend never calls email service directly
          EOF

          # Verify files were created
          if [ ! -f ".env" ] || [ ! -f "services/catalog/.env" ] || [ ! -f "services/checkout/.env" ] || [ ! -f "services/email/.env" ] || [ ! -f "frontend/.env.production" ]; then
            echo "ERROR: Some .env files were not created!"
            exit 1
          fi

          echo "All .env files created successfully"

          # Wait for Docker to be ready
          echo "Waiting for Docker to be ready..."
          sleep 10

          # Verify Docker is running
          if ! systemctl is-active --quiet docker; then
            echo "ERROR: Docker is not running!"
            systemctl status docker
            exit 1
          fi

          # Start services
          echo "Starting Docker Compose services..."
          docker-compose up -d --build

          if [ $? -ne 0 ]; then
            echo "ERROR: Docker Compose failed!"
            echo "Checking logs..."
            docker-compose logs
            exit 1
          fi

          # Wait for services to be ready
          echo "Waiting for services to be ready..."
          sleep 30

          # Verify all containers are running
          echo "Verifying container status..."
          if ! docker-compose ps | grep -q "Up"; then
            echo "WARNING: Some containers may not be running"
            docker-compose ps
          fi

          # Check if frontend container is running and port 80 is listening
          echo "Checking frontend service..."
          sleep 5
          if ! docker ps | grep -q "ecommerce_frontend"; then
            echo "ERROR: Frontend container is not running!"
            docker-compose logs frontend
            exit 1
          fi

          # Test if port 80 is accessible
          if ! curl -f http://localhost > /dev/null 2>&1; then
            echo "WARNING: Port 80 is not responding, checking logs..."
            docker-compose logs frontend --tail=20
          else
            echo "Frontend service is responding on port 80"
          fi

          # Run database migrations
          echo "Running database migrations..."
          docker-compose exec -T catalog php artisan migrate --seed || echo "WARNING: Catalog migration failed"
          docker-compose exec -T checkout php artisan migrate || echo "WARNING: Checkout migration failed"
          docker-compose exec -T email php artisan migrate || echo "WARNING: Email migration failed"

          # Get public IP
          PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)

          # Log completion with detailed status
          echo "Deployment completed successfully!" > /home/ec2-user/deployment-status.txt
          echo "Application URL: http://$PUBLIC_IP" >> /home/ec2-user/deployment-status.txt
          echo "Deployment time: $(date)" >> /home/ec2-user/deployment-status.txt
          echo "" >> /home/ec2-user/deployment-status.txt
          echo "Container status:" >> /home/ec2-user/deployment-status.txt
          docker-compose ps >> /home/ec2-user/deployment-status.txt

          echo ""
          echo "=========================================="
          echo "DEPLOYMENT COMPLETED SUCCESSFULLY!"
          echo "=========================================="
          echo "Application URL: http://$PUBLIC_IP"
          echo "=========================================="

      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ec2'

  # Elastic IP (optional - free if instance is running)
  EIP:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-eip'

  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      InstanceId: !Ref EC2Instance

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EIP.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-PublicIP'

  PublicDNS:
    Description: Public DNS hostname of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName
    Export:
      Name: !Sub '${AWS::StackName}-PublicDNS'

  WebsiteURL:
    Description: Website URL (IP address)
    Value: !Sub 'http://${EIP.PublicIp}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'

  WebsiteURLDNS:
    Description: Website URL (DNS hostname)
    Value: !Sub 'http://${EC2Instance.PublicDnsName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURLDNS'

  SSHCommand:
    Description: SSH command to connect to the instance
    Value: !Sub 'ssh -i dennis-ec2.pem ec2-user@${EIP.PublicIp}'
